--RFC1
SELECT ope.NOMBRE, SUM(cont.PRECIO)
FROM OPERADORES ope, CONTRATOS cont, OFERTAS ofe
WHERE cont.FECHA LIKE '%18' AND cont.ID_OFERTA = ofe.ID AND ope.ID = ofe.ID_OPERADOR
GROUP BY ope.NOMBRE;

--RFC2
SELECT ofe.ID, COUNT(cont.ID) AS NumVeces 
FROM CONTRATOS cont, OFERTAS ofe
WHERE cont.ID_OFERTA = ofe.ID  
GROUP BY ofe.ID
ORDER BY COUNT(cont.ID) DESC
WHERE ROWNUM<20;

--RFC3
SELECT ope.ID, ope.NOMBRE, SUM(res.NUM_PERSONAS)/SUM(ofe.CAPACIDAD) AS PORCENTAJEOCUPACION
FROM OPERADORES ope INNER JOIN OFERTAS ofe ON ope.ID=ofe.ID_OPERADOR INNER JOIN RESERVAS res ON res.ID_OFERTA = ofe.ID
WHERE res.CANCELADA='F' AND '23/03/18' BETWEEN res.FECHA_INICIO AND res.FECHA_FIN
GROUP BY ope.ID,ope.NOMBRE;

--RFC4
SELECT * FROM OFERTAS ofe
WHERE ofe.ID NOT IN 
(SELECT re.ID_OFERTA
FROM  RESERVAS re
WHERE( re.FECHA_INICIO  BETWEEN '27/08/18' AND '02/12/18')
OR  ( re.FECHA_FIN  BETWEEN '27/08/18' AND '02/12/18')
OR (  re.FECHA_INICIO <'27/08/18'  AND   re.FECHA_FIN> '02/12/18'))
AND ofe.ID IN
(SELECT serv.ID_OFERTA
FROM  OFRECEN serv
INNER JOIN  SERVICIOS servi
ON servi.ID=serv.ID_SERVICIO
WHERE servi.NOMBRE='mobile'AND servi.NOMBRE='policy');

--RFC5
SELECT ofe.TIPO AS TIPOALOJAMIENTO,SUM(re.PRECIO_TOTAL) AS COSTO,SUM(re.NUM_DIAS) AS NUMDIAS
FROM CLIENTES cli
INNER JOIN  RESERVAS re
ON re.ID_CLIENTE=cli.ID
INNER JOIN OFERTAS ofe
ON ofe.ID=re.ID_OFERTA
GROUP BY cli.ID_VINCULO,ofe.TIPO;

--RFC6
SELECT cli.ID,  cli.NOMBRE, ofe.TIPO AS TIPOALOJAMIENTO,SUM(re.PRECIO_TOTAL) AS COSTO,SUM(re.NUM_DIAS) AS NUMDIAS
FROM CLIENTES cli
INNER JOIN  RESERVAS re
ON re.ID_CLIENTE=cli.ID
INNER JOIN OFERTAS ofe
ON ofe.ID=re.ID_OFERTA
WHERE cli.NOMBRE='Garek Ivanonko'
GROUP BY cli.NOMBRE,cli.ID,ofe.TIPO;

--RFC7
SELECT COUNT(*) AS OCUPACION  
FROM RESERVAS res 
INNER JOIN OFERTAS ofe 
ON ofe.ID=res.ID_OFERTA 
WHERE "+xi+" 
BETWEEN res.FECHA_INICIO 
AND res.FECHA_FIN  
AND res.CANCELADA='F' 
AND  ofe.TIPO = %1$s"

SELECT SUM(COSTO_DEFINITIVO) AS TOTAL_COBRADO_POR_DIA 
FROM RESERVAS res 
INNER JOIN OFERTAS ofe 
ON res.ID_OFERTA=ofe.ID 
WHERE (res.TERMINADA='T' 
AND res.FECHA_FIN= +xi+  )
OR (res.CANCELADA='T' 
AND res.FECHA_CANCELACION= +xi +) 
AND  ofe.TIPO = $1$S

--RFC8
SELECT res.ID_OFERTA,res.ID_CLIENTE,cli.NOMBRE,cli.CORREO,COUNT(*) AS NUMERO_OCASIONES,SUM(TRUNC(res.FECHA_FIN)-TRUNC(res.FECHA_INICIO)) AS NUM_NOCHES
FROM RESERVAS res 
INNER JOIN CLIENTES cli 
ON cli.ID=res.ID_CLIENTE 
WHERE res.ID_OFERTA = %1$d 
AND res.CANCELADA='F'
GROUP BY res.ID_CLIENTE, res.ID_OFERTA,cli.NOMBRE,cli.CORREO 
HAVING COUNT(*)>=3 
OR SUM(TRUNC(res.FECHA_FIN)-TRUNC(res.FECHA_INICIO)) >=15

--RFC9
SELECT * 
FROM OFERTAS ofe 
WHERE ofe.ID
NOT IN 
( SELECT res.ID_OFERTA 
FROM RESERVAS res 
WHERE( res.FECHA_INICIO  
BETWEEN x1 AND x2 )