--RFC1
SELECT ope.NOMBRE, SUM(cont.PRECIO)
FROM OPERADORES ope, CONTRATOS cont, OFERTAS ofe
WHERE cont.FECHA LIKE '%18' AND cont.ID_OFERTA = ofe.ID AND ope.ID = ofe.ID_OPERADOR
GROUP BY ope.NOMBRE;

--RFC2
SELECT ofe.ID, COUNT(cont.ID) AS NumVeces 
FROM CONTRATOS cont, OFERTAS ofe
WHERE cont.ID_OFERTA = ofe.ID  
GROUP BY ofe.ID
ORDER BY COUNT(cont.ID) DESC
WHERE ROWNUM<20;

--RFC3
SELECT ope.ID, ope.NOMBRE, SUM(res.NUM_PERSONAS)/SUM(ofe.CAPACIDAD) AS PORCENTAJEOCUPACION
FROM OPERADORES ope INNER JOIN OFERTAS ofe ON ope.ID=ofe.ID_OPERADOR INNER JOIN RESERVAS res ON res.ID_OFERTA = ofe.ID
WHERE res.CANCELADA='F' AND '23/03/18' BETWEEN res.FECHA_INICIO AND res.FECHA_FIN
GROUP BY ope.ID,ope.NOMBRE;

--RFC4
SELECT * FROM OFERTAS ofe
WHERE ofe.ID NOT IN 
(SELECT re.ID_OFERTA
FROM  RESERVAS re
WHERE( re.FECHA_INICIO  BETWEEN '27/08/18' AND '02/12/18')
OR  ( re.FECHA_FIN  BETWEEN '27/08/18' AND '02/12/18')
OR (  re.FECHA_INICIO <'27/08/18'  AND   re.FECHA_FIN> '02/12/18'))
AND ofe.ID IN
(SELECT serv.ID_OFERTA
FROM  OFRECEN serv
INNER JOIN  SERVICIOS servi
ON servi.ID=serv.ID_SERVICIO
WHERE servi.NOMBRE='mobile'AND servi.NOMBRE='policy');

--RFC5
SELECT ofe.TIPO AS TIPOALOJAMIENTO,SUM(re.PRECIO_TOTAL) AS COSTO,SUM(re.NUM_DIAS) AS NUMDIAS
FROM CLIENTES cli
INNER JOIN  RESERVAS re
ON re.ID_CLIENTE=cli.ID
INNER JOIN OFERTAS ofe
ON ofe.ID=re.ID_OFERTA
GROUP BY cli.ID_VINCULO,ofe.TIPO;

--RFC6
SELECT cli.ID,  cli.NOMBRE, ofe.TIPO AS TIPOALOJAMIENTO,SUM(re.PRECIO_TOTAL) AS COSTO,SUM(re.NUM_DIAS) AS NUMDIAS
FROM CLIENTES cli
INNER JOIN  RESERVAS re
ON re.ID_CLIENTE=cli.ID
INNER JOIN OFERTAS ofe
ON ofe.ID=re.ID_OFERTA
WHERE cli.NOMBRE='Garek Ivanonko'
GROUP BY cli.NOMBRE,cli.ID,ofe.TIPO;

--RFC7




--RFC8




--RFC9



